- "Entertainment & Media":
    - Jellyfin:
        icon: jellyfin.svg
        href: http://jellyfin.lab
        description: Watch Movies & TV Shows
        server: opi_docker
        container: jellyfin
        showStats: true
        widget:
          type: jellyfin
          url: http://jellyfin.lab
          key: apikey

    - Navidrome:
        icon: navidrome.svg
        href: http://navidrome.lab
        description: Listen To Music
        server: opi_docker
        container: navidrome
        showStats: true
        widget:
          type: navidrome
          url: http://navidrome.lab
          key: api

    - Overseerr:
        icon: overseer.svg
        href: http://overseer.lab
        description: Unifed Place To Request And Manage Media
        server: opi_docker
        container: overseer
        showStats: true
        widget:
            type: overseer
            url: http://overseer.lab
            key: apikey
            fields: ["pending", "approved", "available", "processing"]

    - Radarr:
        icon: radarr.svg
        href: http://radarr.lab
        description: Manage Movie Library
        server: opi_docker
        container: radarr
        showStats: true
        widget:
          type: radarr
          url: http://radarr.lab
          key: apikey
          fields: ["wanted", "missing", "queued", "movies"]

    - Sonarr:
        icon: sonarr.svg
        href: http://sonarr.lab
        description: Manage TV Show Library
        server: opi_docker
        container: sonarr
        showStats: true
        widget:
          type: sonarr
          url: http://sonarr.lab
          key: apikey
          fields: ["wanted", "queued", "series"]

    - Lidarr:
        icon: lidarr.svg
        href: http://lidarr.lab
        description: Manage Music Library
        server: opi_docker
        container: lidarr
        showStats: true
        widget:
          type: lidarr
          url: http://lidarr.lab
          key: apikey
          fields: ["wanted", "queued", "artists"]

    - Bazarr:
        icon: bazarr.svg
        href: http://bazarr.lab
        description: Manage Subtitles
        server: opi_docker
        container: bazarr
        showStats: true
        widget:
          type: bazarr
          url: http://bazarr.lab
          key: apikey
          fields: ["missingEpisodes", "missingMovies"]

    - Prowlarr:
        icon: prowlarr.svg
        href: http://prowlarr.lab
        description: Indexer For Other 'arr' Apps
        server: opi_docker
        container: prowlarr
        showStats: true
        widget:
            type: prowlarr
            url: http://prowlarr.lab
            key: apikey
            fields: ["numberOfGrabs", "numberOfQueries", "numberOfFailGrabs", "numberOfFailQueries"]

    - qBittorrent:
        icon: qbittorrent.svg
        href: http://qbittorrent.lab
        description: Torrent Client For 'arr' Apps
        server: opi_docker
        container: qbittorrent
        showStats: true
        widget:
            type: qbittorrent
            url: http://qbittorrent.lab
            username: username
            password: password
            enableLeechProgress: true
            fields: ["leech", "download", "seed", "upload"]

- "Productivity & Documents":
    - Nextcloud:
        icon: nextcloud.svg
        href: http://nextcloud.lab
        description: Access & Edit Your Files
        server: opi_docker
        container: nextcloud
        showStats: true
        widget:
          type: nextcloud
          url: http://nextcloud.lab
          key: apikey
          fields: ["freespace", "activeusers", "numfiles", "numshares"]

    - Joplin:
        icon: joplin.svg
        href: http://joplin.lab
        description: Note Taking & To-Do Lists
        server: opi_docker
        container: joplin
        showStats: true

    - Immich:
        icon: immich.svg
        href: http://immich.lab
        description: Photo & Video Management
        server: opi_docker
        container: immich
        showStats: true
        widget:
          type: immich
          url: http://immich.lab
          key: apikey
          fields: ["users", "photos", "videos", "storage"]

    - Vikunja:
        icon: vikunja.svg
        href: http://todo.lab
        description: To Do List and Task Manager
        server: opi_docker
        container: vikunja
        showStats: true
        widget:
            type: vikunja
            url: http://todo.lab
            key: apikey
            enableTaskList: true
            fields: ["projects", "task7d", "tasksOverdue", "tasksInProgress"]

    - Bookstack:
        icon: bookstack.svg
        href: http://bookstack.lab
        description: Detailed Documention Writer
        server: opi_docker
        container: bookstack
        showStats: true

    - Fittrack:
        icon: fittrack.svg
        href: http://fittrack.lab
        description: Fittness and Workout Manager
        server: opi_docker
        container: fittrack
        showStats: true

    - Weehealth:
        icon: weehealth.svg
        href: http://weehealth.lab
        description: Weight and Health Tracker
        server: opi_docker
        container: weehealth
        showStats: true

    - Mealie:
        icon: mealie.svg
        href: http://mealie.lab
        description: Meal Planner and Calorie Tracker
        server: opi_docker
        container: mealie
        showStats: true

    - Vaultwarden:
        icon: bitwarden.svg
        href: http://passwords.lab
        description: Password Management
        server: opi_docker
        container: vaultwarden
        showStats: true

    - VS Code Server:
        icon: visual-studio-code.svg
        href: http://vscode.lab
        description: Online Code Editor
        server: opi_docker
        container: vscode_server
        showStats: true

    - Linux VM:
        icon: linux.svg
        href: http://linuxvm.lab
        description: Accessable Linux Virtual Machine

- "Device & Connectivity":
    - Pi-Hole:
        icon: pi-hole.svg
        href: http://pihole.lab
        description: Network-wide Ad Blocking
        server: opi_docker
        container: pihole
        showStats: true
        widget:
          type: pihole
          url: http://pihole.lab
          version: 6
          key: apikey
          fields: ["queries", "blocked", "blocked_percent", "gravity"]

    - Netdata:
        icon: netdata.svg
        href: http://netdata.lab
        description: Real-time Performance Monitoring
        server: opi_docker
        container: netdata
        showStats: true
        widget:
          type: netdata
          url: http://netdata.lab
          fields: ["warnings", "critcals"]

    - Homepage:
        href: http://home.lab
        icon: homepage.png
        description: Dashboard
        server: opi_docker
        container: homepage
        showStats: true

    - Authentik: 
        href: http://auth.lab
        icon: authentik.svg
        description: Global Authentication
        server: opi_docker
        container: authentik
        showStats: true
        widget:
            type: authentik
            url: http://auth.lab
            key: apikey
            version: 2
            fields: ["users", "loginsLast24H", "faildLogins24H"]

    - Watchtower:
        icon: watchtower.svg
        href: http://watchtower.lab
        description: Monitor & Update Containers
        server: opi_docker
        container: watchtower
        showStats: true
        widget:
            type: watchtower
            url: http://watchtower.lab
            key: apikey
            fields: ["containers_scanned", "containers_updated", "containers_failed"]

    - Tailscale:
        icon: tailscale.svg
        href: http://donthaveoneyet
        description: Secure VPN Access To The Orange Pi
        server: opi_docker
        container: tailscale
        showStats: true

    - Traefik:
        icon: traefik.svg
        href: http://traefik.lab
        description: Correctly Route Incoming Traffic
        server: opi_docker
        container: traefik
        showStats: true
        widget:
            type: traefik
            url: http://traefik.lab
            username: username
            password: 
            fields: ["routers", "services", "middleware"]

    - Gluetun:
        icon: gluetun.svg
        href: http://gluetun.lab
        description: VPN Container 
        server: opi_docker
        container: gluetun
        showStats: true
        widget:
            type: gluetun
            url: http://gluetun.lab
            key: apikey
            version: 2
            fields: ["public_ip", "region", "country", "port_forwarded"]

    - Minecraft Server:
        icon: minecraft.svg
        href: http://donthaveoneyet
        description: Monitor Minecraft Server
        server: opi_docker
        container: mc_server
        showStats: true
        widget:
          type: minecraft
          url: udp://donthaveoneyet:25565
          fields: ["players", "version", "status"]