- search:
    provider: duckduckgo
    focus: false
    showSearchSuggestions: false
    target: _self

- datetime:
    text_size: md
    format:
      dataStyle: short
      timeStyle: short
      hourCycle: h23

- openmeteo: 
    label: Stoke-On-Trent
    latitude: 53.002666
    longitude: -2.17944
    units: metric
    cache: 5

- resources:
    label: CPU
    cpu: true
    cputemp: true
    expanded: true
    units: metric

- resources: 
    label: Memory
    memory: true

- resources:
    label: Storage
    disk: /temp_file_path/

- resources:
    label: Uptime
    uptime: true
  
