- logo:
    icon: C:\docker\homepage\images\logo.png

- search:
    provider: duckduckgo
    focus: false
    showSearchSuggestions: true
    target: _self

- datetime:
    text_size: md
    format:
      dateStyle: short
      timeStyle: short
      hourCycle: h23

- openmeteo: 
    label: Stoke
    latitude: 53.002666
    longitude: -2.17944
    units: metric
    cache: 5

- resources:
    label: Resources
    cpu: true
    cputemp: true
    memory: true
    disk: C:/
    uptime: true
    expanded: true
    units: metric

- resources: 
    label: Memory
    memory: true

- resources:
    label: Storage
    disk: /temp_file_path/

- resources:
    label: Uptime
    uptime: true
  
